---
# Source: demo-pipeline/templates/job-good.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: trigger-java-app-build-good
  namespace: demo-application4
spec:
  template:
    spec:
      serviceAccountName: pipeline
      containers:
      - name: kubectl-runner
        image: registry.redhat.io/openshift4/ose-cli:latest
        command:
          - /bin/sh
          - -c
          - |
            # This 'here document' passes the PipelineRun YAML directly to oc.
            # It tells Tekton to start a new run of the 'java-app-build' pipeline.
            oc create -f - <<EOF
            apiVersion: tekton.dev/v1
            kind: PipelineRun
            metadata:
              # generateName creates a unique name for each run (e.g., java-app-build-run-abc12).
              generateName: java-app-build-run-good-
              namespace: demo-application4
            spec:
              taskRunTemplate:
                serviceAccountName: pipeline
              pipelineRef:
                # This must match the name of your existing Tekton Pipeline.
                name: java-app-build
              # Parameters for the pipeline - using "good" git revision as requested
              params:
                - name: IMAGE_NAME
                  value: "image-registry.openshift-image-registry.svc:5000/demo-application4/undertow-servlet"
                - name: GIT_REPO
                  value: "https://github.com/nstrug/openshift-quickstarts.git"
                - name: GIT_REVISION
                  value: "good"
                - name: SUBDIRECTORY
                  value: "undertow-servlet"
              # Required workspace for the pipeline
              workspaces:
                - name: shared-workspace
                  volumeClaimTemplate:
                    spec:
                      accessModes:
                        - ReadWriteOnce
                      resources:
                        requests:
                          storage: 3Gi
            EOF
      restartPolicy: OnFailure
