kind: PipelineRun
spec:
  params:
    - name: IMAGE_NAME
      value: 'image-registry.openshift-image-registry.svc:5000/demo-application3/undertow-servlet'
    - name: GIT_REPO
      value: 'https://github.com/nstrug/openshift-quickstarts.git'
    - name: GIT_REVISION
      value: good
    - name: SUBDIRECTORY
      value: undertow-servlet
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: shared-workspace
      emptyDir: {}
  pipelineRef:
    name: java-app-build
  taskRunTemplate:
    serviceAccountName: pipeline