apiVersion: batch/v1
kind: Job
metadata:
  name: trigger-java-app-build-good
  namespace: demo-application3
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: pipeline-trigger-sa
      containers:
      - name: kubectl-runner
        image: registry.redhat.io/openshift4/ose-cli:latest
        command:
          - /bin/sh
          - -c
          - |
            # This 'here document' passes the PipelineRun YAML directly to oc.
            # It tells Tekton to start a new run of the 'java-app-build' pipeline.
            oc apply -f - <<EOF
            apiVersion: tekton.dev/v1
            kind: PipelineRun
            metadata:
              # generateName creates a unique name for each run (e.g., java-app-build-run-abc12).
              generateName: java-app-build-run-good-
              namespace: demo-application3
            spec:
              pipelineRef:
                # This must match the name of your existing Tekton Pipeline.
                name: java-app-build
              # Parameters for the pipeline - using "good" git revision as requested
              params:
                - name: IMAGE_NAME
                  value: "image-registry.openshift-image-registry.svc:5000/demo-application3/undertow-servlet"
                - name: GIT_REPO
                  value: "https://github.com/nstrug/openshift-quickstarts.git"
                - name: GIT_REVISION
                  value: "good"
                - name: SUBDIRECTORY
                  value: "undertow-servlet"
              # Required workspace for the pipeline
              workspaces:
                - name: shared-workspace
                  volumeClaimTemplate:
                    spec:
                      accessModes:
                        - ReadWriteOnce
                      resources:
                        requests:
                          storage: 1Gi
            EOF
      restartPolicy: OnFailure
---
# REQUIRED: RBAC for the Job's Service Account
# This gives the Job permission to create PipelineRuns.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-trigger-sa
  namespace: demo-application3
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-run-creator
  namespace: demo-application3
rules:
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns"]
  verbs: ["create", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-trigger-binding
  namespace: demo-application3
subjects:
- kind: ServiceAccount
  name: pipeline-trigger-sa
roleRef:
  kind: Role
  name: pipeline-run-creator
  apiGroup: rbac.authorization.k8s.io