apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-pipelines-edit
  namespace: demo-application3
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: demo-application3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
