---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-etx-terminal
  namespace: openshift-terminal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
---
apiVersion: workspace.devfile.io/v1alpha1
kind: DevWorkspace
metadata:
  name: etx-terminal
  generateName: etx-terminal
  labels:
    console.openshift.io/terminal: 'true'
  annotations:
    controller.devfile.io/restricted-access: 'true'
  namespace: openshift-terminal
spec:
  routingClass: web-terminal
  started: true
  template:
    components:
      - name: web-terminal-tooling
        plugin:
          kubernetes:
            name: web-terminal-tooling
            namespace: openshift-operators
          components:
          - container:
              image: quay.io/eformat/web-terminal:latest-x86_64
            name: web-terminal-tooling
          volumeMounts:
            - name: claim-etx-terminal
              path: "/home/user"
      - name: web-terminal-exec
        plugin:
          kubernetes:
            name: web-terminal-exec
            namespace: openshift-operators
      - volume:
          name: claim-etx-terminal
