---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: dev-red-rag-colbert
    app.kubernetes.io/component: dev-red-rag-colbert
    app.kubernetes.io/instance: dev-red-rag-colbert
  name: dev-red-rag-colbert
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: quay.io/eformat/dev-red-rag-colbert:latest
    importPolicy:
      importMode: Legacy
    name: latest
    referencePolicy:
      type: Source
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: dev-red-rag-colbert
    app.kubernetes.io/component: dev-red-rag-colbert
    app.kubernetes.io/instance: dev-red-rag-colbert
  name: dev-red-rag-colbert
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8081-tcp
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    deployment: dev-red-rag-colbert
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "11"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"dev-red-rag-colbert:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"dev-red-rag-colbert\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: dev-red-rag-colbert
    app.kubernetes.io/component: dev-red-rag-colbert
    app.kubernetes.io/instance: dev-red-rag-colbert
  name: dev-red-rag-colbert
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: dev-red-rag-colbert
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        deployment: dev-red-rag-colbert
    spec:
      containers:
      - image: ' '
        imagePullPolicy: Always
        name: dev-red-rag-colbert
        ports:
        - containerPort: 8081
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            nvidia.com/gpu: "1"
          requests:
            nvidia.com/gpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: dev-red-rag-colbert
    app.kubernetes.io/component: dev-red-rag-colbert
    app.kubernetes.io/instance: dev-red-rag-colbert
  name: dev-red-rag-colbert
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dev-red-rag-colbert
    weight: 100
  wildcardPolicy: None
status: {}
