apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: undertow-servlet
    app.kubernetes.io/component: undertow-servlet
    app.kubernetes.io/instance: undertow-servlet
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: demo-application
    meta.helm.sh/release-namespace: demo-application
    openshift.io/host.generated: 'true'
  name: {{ .Values.application_name }}
  namespace: {{ .Values.namespace }}
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: undertow-servlet
    weight: 100
  wildcardPolicy: None
  tls:
    termination: edge