apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.application_name }}
    app.kubernetes.io/component: {{ .Values.application_name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    openshift.io/host.generated: 'true'
  name: {{ .Values.application_name }}
  namespace: {{ .Values.namespace }}
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: {{ .Values.application_name }}
    weight: 100
  wildcardPolicy: None
  tls:
    termination: edge