apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.application_name }}
    app.kubernetes.io/component: {{ .Values.application_name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  name: {{ .Values.application_name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    deployment: {{ .Values.application_name }}