---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: network-policy-vllm-server-sno
  annotations:
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/controls: SC-8 Transmission Confidentiality and Integrity
    policy.open-cluster-management.io/description: NetworkPolicy for llama-stack
    policy.open-cluster-management.io/standards: NIST SP 800-53
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: network-policy-vllm-server-sno
      spec:
        object-templates:
        - complianceType: mustonlyhave
          objectDefinition:
            apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-from-llama-stack
              namespace: vllm-server
            spec:
              podSelector: {}
              ingress:
              - from:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: llama-stack
        remediationAction: inform
        severity: low
  remediationAction: enforce