apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: {{ .Values.namespace }}
immutable: false
data:
  CLIENT_TIMEOUT: {{ .Values.agentConfig.clientTimeout | quote }}
  LLAMA_STACK_URL: {{ .Values.agentConfig.llamaStackUrl | quote }}
  MAX_INFER_ITERATIONS: {{ .Values.agentConfig.maxInferIterations | quote }}
  MAX_TOKENS: {{ .Values.agentConfig.maxTokens | quote }}
  MODEL_ID: {{ .Values.agentConfig.modelId | quote }}
  TEMPERATURE: {{ .Values.agentConfig.temperature | quote }} 