apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.application_name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.application_name }}
    app.kubernetes.io/component: {{ .Values.application_name }}
    app.kubernetes.io/instance: {{ .Values.application_name }}
    app.kubernetes.io/name: {{ .Values.application_name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    app.openshift.io/vcs-ref: {{ .Values.git_revision | default "" | quote }}
    app.openshift.io/vcs-uri: {{ .Values.git_url | quote }}
    openshift.io/generated-by: OpenShiftWebConsole
    openshift.io/host.generated: 'true'
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  to:
    kind: Service
    name: {{ .Values.application_name }}
    weight: 100
  port:
    targetPort: 8000-tcp
  wildcardPolicy: None