apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application_name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.application_name }}
    app.kubernetes.io/component: {{ .Values.application_name }}
    app.kubernetes.io/instance: {{ .Values.application_name }}
    app.kubernetes.io/name: {{ .Values.application_name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    app.openshift.io/vcs-ref: {{ .Values.git_revision | default "" | quote }}
    app.openshift.io/vcs-uri: {{ .Values.git_url | quote }}
    openshift.io/generated-by: OpenShiftWebConsole
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: 8000-tcp
    protocol: TCP
    port: 8000
    targetPort: 8000
  internalTrafficPolicy: Cluster
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: {{ .Values.application_name }}
    deployment: {{ .Values.application_name }}