---
# Source: ai-agent/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-pipelines-edit
  namespace: ai-agent
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: ai-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
