---
# Source: demo-pipeline/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-pipelines-edit
  namespace: demo-pipeline
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: demo-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
